(async function initHome() {
  const data = await loadRgxData();
  applySocialLinks(data.settings && data.settings.socialLinks);
  renderPosts(data.posts || []);
  renderDownloads(data.files || []);
  wireSearch();
})();

function renderPosts(posts) {
  const active = posts.filter((post) => post.active !== false).slice().reverse();
  const latestTitle = document.querySelector("#latestTitle");
  const pinned = document.querySelector("#pinnedPost");
  const grid = document.querySelector("#postGrid");
  const popular = document.querySelector("#popularPosts");

  if (!active.length) {
    latestTitle.textContent = "No post published yet.";
    pinned.innerHTML = emptyCard("No pinned post", "Create a post from the admin panel.");
    grid.innerHTML = emptyCard("No stories yet", "New RGX posts will appear here.");
    popular.innerHTML = "<p>No posts yet.</p>";
    return;
  }

  latestTitle.textContent = active[0].title || "RGX Post";
  pinned.innerHTML = postCard(active[0], true);
  grid.innerHTML = active.map((post) => postCard(post, false)).join("");
  renderLabels(active);
  popular.innerHTML = active.slice(0, 5).map((post) => `
    <a href="./post.html?id=${encodeURIComponent(post.id)}">${escapeHtml(post.title || "RGX Post")}</a>
  `).join("");
}

function renderDownloads(files) {
  const list = document.querySelector("#downloadList");
  const active = files.filter((file) => file.active !== false).slice().reverse();

  if (!active.length) {
    list.innerHTML = emptyCard("No downloads yet", "Bot generated download links will appear here.");
    return;
  }

  list.innerHTML = active.map((file) => {
    const size = file.sizeLabel ? `<p>${escapeHtml(file.sizeLabel)}</p>` : "";
    const title = file.fileName || file.title || "RGX File";
    return `
      <article class="story-card download-story">
        <div class="file-badge"><span>${escapeHtml(file.extension || "FILE")}</span></div>
        <h3>${escapeHtml(title)}</h3>
        <small class="story-meta">${escapeHtml(file.createdAt ? new Date(file.createdAt).toLocaleDateString() : "Generated by bot")}</small>
        ${size}
        <a class="read-more" href="./download.html?id=${encodeURIComponent(file.id)}">Download Now</a>
      </article>
    `;
  }).join("");
}

function postCard(post, pinned) {
  const href = `./post.html?id=${encodeURIComponent(post.id)}`;
  return `
    <article class="${pinned ? "story-card pinned-card" : "story-card"}">
      ${post.image ? `<a href="${href}"><img src="${post.image}" alt="${escapeHtml(post.title || "RGX Post")}"></a>` : ""}
      <div>
        <small class="story-meta">${escapeHtml(post.category || "Downloads")} • ${escapeHtml(post.createdAt ? new Date(post.createdAt).toLocaleDateString() : "RGX")}</small>
        <h3><a href="${href}">${escapeHtml(post.title || "RGX Post")}</a></h3>
        ${post.subtitle ? `<p>${escapeHtml(post.subtitle)}</p>` : ""}
        ${post.description ? `<p>${escapeHtml(trim(post.description, pinned ? 160 : 92))}</p>` : ""}
        <a class="read-more" href="${href}">Read More</a>
      </div>
    </article>
  `;
}

function renderLabels(posts) {
  const target = document.querySelector("#labelCloud");
  if (!target) return;
  const counts = posts.reduce((map, post) => {
    const label = post.category || "Downloads";
    map.set(label, (map.get(label) || 0) + 1);
    return map;
  }, new Map());
  target.innerHTML = [...counts.entries()].map(([label, count]) => `<span>${escapeHtml(label)} <b>${count}</b></span>`).join("");
}

function wireSearch() {
  const input = document.querySelector("#siteSearch");
  if (!input) return;
  input.addEventListener("input", () => {
    const query = input.value.trim().toLowerCase();
    document.querySelectorAll(".story-card").forEach((card) => {
      const text = card.textContent.toLowerCase();
      card.classList.toggle("filtered-out", query && !text.includes(query));
    });
  });
}

function emptyCard(title, text) {
  return `<article class="story-card empty-card"><h3>${escapeHtml(title)}</h3><p>${escapeHtml(text)}</p></article>`;
}

function applySocialLinks(links = {}) {
  const map = {
    youtube: document.querySelector('[data-social="youtube"]'),
    telegram: document.querySelector('[data-social="telegram"]'),
    instagram: document.querySelector('[data-social="instagram"]')
  };

  Object.entries(map).forEach(([key, element]) => {
    if (element && links[key]) element.href = links[key];
  });
}

function trim(value, length) {
  const text = String(value || "");
  return text.length > length ? `${text.slice(0, length - 1)}...` : text;
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
